### ISSUE TITLE
SyntaxError: invalid syntax base.py line 476

### ISSUE THREAD

**Issue by adargu** [welbornprod/colr#1]
File "/usr/local/lib/python3.4/dist-packages/Colr-0.8.1-py3.4.egg/colr/base.py", line 476
    **kwargs,
            ^
SyntaxError: invalid syntax

**Comment by cjwelborn** [comment]
Can you tell me what it would take to reproduce this on my machine? Like what you were doing when this was triggered?

**Comment by adargu** [comment]
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# coding: UTF-8

from colr import color
print(color('Hello world.', fore='red', style='bright'))
```

bash$ ./colr.py
Traceback (most recent call last):
  File "./colr.py", line 5, in <module>
    from colr import color
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/Colr-0.8.1-py3.4.egg/colr/__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1916, in _get_spec
  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location
  File "/usr/local/lib/python3.4/dist-packages/Colr-0.8.1-py3.4.egg/colr/base.py", line 476
    **kwargs,
            ^
SyntaxError: invalid syntax

**Comment by adargu** [comment]
Also:

$ sudo -H pip3 install colr
Downloading/unpacking colr
  Downloading Colr-0.8.1.tar.gz (89kB): 89kB downloaded
  Running setup.py (path:/tmp/pip-build-aue0d8_8/colr/setup.py) egg_info for package colr

Installing collected packages: colr
  Running setup.py install for colr
      File "/usr/local/lib/python3.4/dist-packages/colr/base.py", line 476
        **kwargs,
                ^
    SyntaxError: invalid syntax

      File "/usr/local/lib/python3.4/dist-packages/colr/progress_frames.py", line 248
        **clsargs,
                 ^
    SyntaxError: invalid syntax


    Installing colr script to /usr/local/bin
Successfully installed colr
Cleaning up...

**Comment by adargu** [comment]
Cloning from GitHub and installing it from command line:

# python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing Colr.egg-info/PKG-INFO
writing dependency_links to Colr.egg-info/dependency_links.txt
writing entry points to Colr.egg-info/entry_points.txt
writing top-level names to Colr.egg-info/top_level.txt
reading manifest file 'Colr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Colr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/base.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/colr_docopt.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/__init__.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/name_data.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/control_codes.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/colr.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/progress_frames.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/__main__.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/progress.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/trans.py -> build/bdist.linux-armv7l/egg/colr
copying build/lib/colr/controls.py -> build/bdist.linux-armv7l/egg/colr
byte-compiling build/bdist.linux-armv7l/egg/colr/base.py to base.cpython-34.pyc
  File "build/bdist.linux-armv7l/egg/colr/base.py", line 476
    **kwargs,
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/colr/colr_docopt.py to colr_docopt.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/name_data.py to name_data.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/control_codes.py to control_codes.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/colr.py to colr.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/progress_frames.py to progress_frames.cpython-34.pyc
  File "build/bdist.linux-armv7l/egg/colr/progress_frames.py", line 248
    **clsargs,
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/colr/__main__.py to __main__.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/progress.py to progress.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/trans.py to trans.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/colr/controls.py to controls.cpython-34.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying Colr.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Colr.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Colr.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Colr.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Colr.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Colr-0.8.1-py3.4.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing Colr-0.8.1-py3.4.egg
Copying Colr-0.8.1-py3.4.egg to /usr/local/lib/python3.4/dist-packages
Adding Colr 0.8.1 to easy-install.pth file
Installing colr script to /usr/local/bin

Installed /usr/local/lib/python3.4/dist-packages/Colr-0.8.1-py3.4.egg
Processing dependencies for Colr==0.8.1
Finished processing dependencies for Colr==0.8.1

**Comment by cjwelborn** [comment]
The Colr module can only be used with Python 3.5+. There were many changes between 3.4 and 3.5 that Colr takes advantage of. It's listed in the readme under "Dependencies".

Please upgrade to the latest Python version, and let me know if you have any more trouble. Thanks for trying Colr😀.

**Comment by cjwelborn** [comment]
I believe the problem was dict-unpacking, which was extended in 3.5 to be usable in more situations ( [PEP 448](https://www.python.org/dev/peps/pep-0448/) ).

**Comment by adargu** [comment]
Sorry for the inconvenience, I didn't recognize that my testing environment (raspian) has only python version 3.4.2. I saw the requirement of Python 3.5+ but only checked the productive system...

**Comment by cjwelborn** [comment]
@adargu, no problem. I need to see about getting this working for raspbian now that I know, as I own a few raspberry pis also.
