### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Gabrieldaboss65** [welbornprod/colr#4]
text is completly normal, using multiple of the example methods

**Comment by cjwelborn** [comment]
What operating system are you using?

What part of colr are you using? How are you using it?

"doesn't work" could mean a lot of things. I need an example of what you have tried, and what failed.

**Comment by cjwelborn** [comment]
Closing this issue because it's not an actual bug report. You can open a new issue with an example of what you've tried, what went wrong, possibly with a stack-trace or a screenshot. I'll be glad to help with whatever problem you're having with Colr, as soon as I find out what that is.
