### ISSUE TITLE
doesnt work 2: electric boogalo

### ISSUE THREAD

**Issue by Directory** [welbornprod/colr#5]
#4 
windows 10 and debian linux

python 3.7

putty through ssh and whatever IDEa is.

256 color, true colors and hex examples in the readme.

**Comment by cjwelborn** [comment]
Thanks for that, it helps. That's quite a combination (not unheard of though). My first thought is that something in that chain of software doesn't support ansi escape codes at all. Does this do anything in that setup?:

```bash
echo -e "\x1b[31mRed text.\x1b[0mBack to normal."
```

My second thought is that windows is being detected by Colr, and the colorama support that windows needs is getting in the way. That idea can be tested by disabling the colorama wrapper like this:
```bash
COLR_NO_COLORAMA=1 colr test red
```

Or in python:
```python
import os
os.environ['COLR_NO_COLORAMA'] = '1'
from colr import Colr
print(Colr('test', 'red'))
```

If either of those work, I can look into better windows detection when running over ssh. Windows 10 is supposed to support ansi escape codes these day (not sure if they completed that feature), so I may end up removing the windows-check entirely.

I don't have a windows testing environment, so I may be missing something entirely. I'll see what I can do to reproduce the issue.

Would it be possible for you to post a screenshot of the stuff you're trying so I can see what the code is running on, and what it's being displayed on?

**Comment by cjwelborn** [comment]
I found something, I may be able to drop the colorama hack completely. I'll have to look into it.

**Comment by cjwelborn** [comment]
Try this:
```python
import colr
colr.enable()
print(colr.Colr('test', 'red'))
```

If that works, I know what I need to do.

**Comment by cjwelborn** [comment]
I never liked the colorama hack anyway. It's another dependency, on a library that made me want to write Colr in the first place, and it was thrown together too fast just to get some of my tools working at my day job (they only run Windows, I only run Linux at home). This new method will be more universal. I just hope the colr.controls don't have to change dramatically to support windows.

**Comment by cjwelborn** [comment]
@Gabrieldaboss65, can you try the latest version (0.9.1), and let me know how that works for you?

```bash
pip install --upgrade colr
```

**Comment by cjwelborn** [comment]
@Directory, does the latest version (on PyPi) work for you? If so, I'm gonna close this issue. Either way, let me know.

**Comment by Directory** [comment]
yes it works, sorry i didn't respond sooner but i no longer needed a color print library but yes it works great. I will consider using this library for future projects if i ever need fancy terminal printing.
