### ISSUE TITLE
Remove coloring markup

### ISSUE THREAD

**Issue by italomaia-bk** [welbornprod/colr#6]
Is it possible to remove coloring markup with color?

**Comment by cjwelborn** [comment]
If you're talking about removing escape codes from a string, then yes. If it's already a `Colr` object, call `mything.stripped()`. If it's just a string, then use `strip_codes()`:

```python
from colr import strip_codes

mystring = '\x1b[31mTest\x1b[0m'
print(mystring)
print(strip_codes(mystring))
```

This also doable with the command-line tool:
```bash
echo -e "\x1b[31mTest\x1b[0m" | colr --stripcodes
```

I'm using my phone at the moment, so if I've made an error please excuse me, but the point is that Colr can strip escape codes using several different methods.

You can also disable the codes from being created at all with `colr.disable()`.

Also, Colr already strips codes when calculating the width for justification (ljust, rjust, center).

**Comment by cjwelborn** [comment]
@italomaia-bk, if this answered your question I'm gonna go ahead and close this issue. If not, please explain in a little more detail.
